# This is a basic workflow to help you get started with Actions

name: prisma-heroku-cicd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
      - develop
      - test
    paths:
      - "prisma/**"
      - "heroku/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out 
        uses: actions/checkout@v2

      - name: Run npm ci
        run: npm ci

      # Runs a single command using the runners shell
      - name: Run prisma deploy
        run: npm run prisma:deploy
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy Heroku metadata
        run: |
          cd hasura/server-config
          npx hasura metadata apply --endpoint ${{ secrets.HASURA-ENDPOINT }} --admin-secret ${{ secrets.HASURA-ADMIN-SECRET}}

